apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-svc-2-config
data:
  AWS_REGION: us-east-2
  SQS_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/315073111691/sqs-python
  DB_HOST: database-2.c7o6esgncobt.us-east-2.rds.amazonaws.com
  DB_USER: admin
  DB_NAME: rdssqspy
  DB_TABLE: sqsinfo